export const ADD_TODO = "ADD_TODO";
export const CHANGE_FILTER = "CHANGE_FILTER";
export const COMPLETE_TODO = "COMPLETE_TODO";
export const CANCEL_COMPLETED_TODO = "CANCEL_COMPLETED_TODO";
export const UPDATE_TODO_CONTENT = "UPDATE_TODO_CONTENT";
export const UPDATE_TODO = "UPDATE_TODO";
export const DELETE_TODO = "DELETE_TODO";

